name: Deploy to Surge

on:
  push:
    branches:
      - main  # Despliega cuando se hace push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usar la última versión de Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clona tu código

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Configura Node.js
        with:
          node-version: '16'  # Usar la versión 16 de Node.js

      - name: Install Surge
        run: npm install --global surge  # Instalar Surge

      - name: Deploy to Surge
        run: surge --project ./ --domain nombre-nuevo.surge.sh

        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # Utiliza el token de Surge que configuraste como secreto
