name: Deploy to Surge

on:
  push:
    branches:
      - main  # Despliega cuando hay un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usar la última versión de Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Usar la versión más reciente de checkout

      - name: Install Surge
        run: npm install --global surge  # Instalar Surge

      - name: Deploy to Surge
        run: surge --project ./ --domain nombre-nuevo.surge.sh  # Desplegar al nuevo dominio
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # Usar el token de Surge
