name: Deploy to Surge

on:
  push:
    branches:
      - master  # Asegúrate de que esto coincida con la rama que estás usando

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usar la última versión de Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge  # Instalar Surge

      - name: Deploy to Surge
        run: surge --project ./ --domain nombre-nuevo.surge.sh  # Usa tu dominio personalizado
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}  # Utiliza el token de Surge que configuraste como secreto
